### ISSUE TITLE
Posting solutions is against the Coursera Honor Code

### ISSUE THREAD

**Issue by jchochli** [jbutewicz/Programming-Mobile-Applications-for-Android-Handheld-Systems#1]
This is against the [Coursera Honor Code](https://www.coursera.org/about/terms)

... 3. I will not make solutions to homework, quizzes or exams available to anyone else. This includes both solutions written by me, as well as any official solutions provided by the course staff.

**Comment by jbutewicz** [comment]
James,

I'll have to add this to a private repo when I get a chance.

Thanks,
Joe

**Comment by jchochli** [comment]
No problem, was just giving you a heads up.  Your repo shows up near the top when searching for the class repo because of stars and forks count.  BitBucket offers free private repos by the way.

**Comment by jbutewicz** [comment]
Sweet. BitBucket sounds perfect. I had no idea this would show up in
Google.
